{{- range $name, $app := .Values.apps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  namespace: {{ $.Values.namespace }}
data:
{{- range $key, $value := $app.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{- end }}
