{{- range $name, $app := .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ $app.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $app.image.repository }}:{{ $app.image.tag }}"
          imagePullPolicy: {{ $app.image.pullPolicy }}
          ports:
            - containerPort: {{ $app.port }}
          envFrom:
            - configMapRef:
                name: {{ $name }}-config
            - secretRef:
                name: {{ $name }}-secret
---
{{- end }}
